#ifndef URING_API_COMPLETION_KINDS_H
#define URING_API_COMPLETION_KINDS_H

/* Semantic completion kinds for uring-api. Values are stable across releases. */

#define URING_API_COMPLETION_KIND_RECV 1
#define URING_API_COMPLETION_KIND_SEND 2
#define URING_API_COMPLETION_KIND_WAKE 3
#define URING_API_COMPLETION_KIND_SENDTO 4
#define URING_API_COMPLETION_KIND_RECVMSG 5
#define URING_API_COMPLETION_KIND_ACCEPT 6
#define URING_API_COMPLETION_KIND_CONNECT 7
#define URING_API_COMPLETION_KIND_CANCEL 8
#define URING_API_COMPLETION_KIND_SHUTDOWN 9
#define URING_API_COMPLETION_KIND_CLOSE 10
#define URING_API_COMPLETION_KIND_SENDMSG 11
#define URING_API_COMPLETION_KIND_SOCKET 12
#define URING_API_COMPLETION_KIND_RECV_MULTISHOT 13
#define URING_API_COMPLETION_KIND_SEND_ZC 14
#define URING_API_COMPLETION_KIND_SENDMSG_ZC 15
#define URING_API_COMPLETION_KIND_RECV_BUF 16
#define URING_API_COMPLETION_KIND_POLL 17
#define URING_API_COMPLETION_KIND_POLL_MULTISHOT 18
#define URING_API_COMPLETION_KIND_POLL_REMOVE 19
#define URING_API_COMPLETION_KIND_READ 20
#define URING_API_COMPLETION_KIND_WRITE 21
#define URING_API_COMPLETION_KIND_OPENAT 22

#endif