"""Native stream interfaces.

``StreamReader`` / ``StreamWriter`` are the default concrete pair. ``SSLStream``
implements both, so ``wrap_ssl`` can return ``(stream, stream)``.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Protocol

__all__ = ["ReadStream", "WriteStream"]


class ReadStream(Protocol):
    """Readable half of a native tealet stream pair."""

    @property
    def at_eof(self) -> bool: ...

    def close(self) -> None: ...

    def read(self, n: int = -1) -> bytes: ...

    def readinto(self, b: Any) -> int: ...

    def readexactly(self, n: int) -> bytes: ...

    def readline(self) -> bytes: ...


class WriteStream(Protocol):
    """Writable half of a native tealet stream pair."""

    def get_extra_info(self, name: str, default: Any = None) -> Any: ...

    def handshake(self) -> None: ...

    def write(self, data: bytes | bytearray | memoryview) -> None: ...

    def writelines(self, lines: Iterable[bytes | bytearray | memoryview]) -> None: ...

    def close(self) -> None: ...

    def is_closing(self) -> bool: ...

    def drain(self) -> None: ...

    def flush(self) -> None: ...

    def set_write_buffer_limits(self, high: int | None = None, low: int | None = None) -> None: ...

    def can_write_eof(self) -> bool: ...

    def write_eof(self) -> None: ...

    def wait_closed(self) -> None: ...
