from types import TracebackType

__liburing_version__: str

class Ring:
    def __init__(self, entries: int = 8, flags: int = 0) -> None: ...
    @property
    def fd(self) -> int: ...
    @property
    def features(self) -> int: ...
    @property
    def sq_entries(self) -> int: ...
    @property
    def cq_entries(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Ring: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

def probe(entries: int = 2, flags: int = 0) -> dict[str, object]: ...
