from types import TracebackType
from collections.abc import Callable
from typing import Any, TypeAlias

# Non-negative byte offset for submit_read/submit_write (negative values raise ValueError).
FileOffset: TypeAlias = int

__liburing_version__: str
__compiled_liburing_version__: str
__compiled_liburing_version_info__: tuple[int, int]
C_API_ABI_VERSION: int
C_API_STRUCT_SIZE: int
C_API_FEATURE_CORE: int
C_API_FEATURES: int
IORING_SETUP_CQSIZE: int
IORING_SETUP_CLAMP: int
IORING_SETUP_COOP_TASKRUN: int
IORING_SETUP_TASKRUN_FLAG: int
IORING_SETUP_SINGLE_ISSUER: int
IORING_SETUP_DEFER_TASKRUN: int
IORING_CQE_F_MORE: int
IORING_CQE_F_NOTIF: int
IORING_SEND_ZC_REPORT_USAGE: int
IORING_NOTIF_USAGE_ZC_COPIED: int
COMPLETION_KIND_RECV: int
COMPLETION_KIND_RECV_MULTISHOT: int
COMPLETION_KIND_RECV_BUF: int
COMPLETION_KIND_READ: int
COMPLETION_KIND_WRITE: int
COMPLETION_KIND_OPENAT: int
COMPLETION_KIND_STATX: int
COMPLETION_KIND_STATX_FDSIZE: int
AT_FDCWD: int
AT_EMPTY_PATH: int
STATX_BASIC_STATS: int
STATX_SIZE: int
STATX_BUFFER_SIZE: int
STATX_STX_SIZE_OFFSET: int
COMPLETION_KIND_SEND: int
COMPLETION_KIND_SEND_ZC: int
COMPLETION_KIND_WAKE: int
COMPLETION_KIND_SENDTO: int
COMPLETION_KIND_RECVMSG: int
COMPLETION_KIND_ACCEPT: int
COMPLETION_KIND_CONNECT: int
COMPLETION_KIND_CANCEL: int
COMPLETION_KIND_SHUTDOWN: int
COMPLETION_KIND_CLOSE: int
COMPLETION_KIND_SENDMSG: int
COMPLETION_KIND_SENDMSG_ZC: int
COMPLETION_KIND_SOCKET: int
COMPLETION_KIND_POLL: int
COMPLETION_KIND_POLL_MULTISHOT: int
COMPLETION_KIND_POLL_REMOVE: int

class SubmissionQueueFull(RuntimeError): ...

class BufGroup:
    @property
    def buffer_size(self) -> int: ...
    @property
    def buffer_count(self) -> int: ...
    @property
    def leased_count(self) -> int: ...
    @property
    def group_id(self) -> int: ...
    @property
    def ring(self) -> Ring | None: ...

class BufView:
    @property
    def length(self) -> int: ...
    @property
    def buffer_id(self) -> int: ...
    @property
    def buf_group(self) -> BufGroup | None: ...
    @property
    def recycled(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def close(self) -> None: ...

class Completion:
    @property
    def user_data(self) -> object: ...
    @property
    def kind(self) -> int: ...
    @property
    def res(self) -> int: ...
    @property
    def flags(self) -> int: ...
    @property
    def result(self) -> object: ...
    @property
    def sequence(self) -> int: ...
    @property
    def multishot(self) -> bool: ...
    @property
    def cancel_target(self) -> object: ...

class Ring:
    def __init__(self, entries: int = 8, flags: int = 0) -> None: ...
    @property
    def fd(self) -> int: ...
    @property
    def features(self) -> int: ...
    @property
    def sq_entries(self) -> int: ...
    @property
    def cq_entries(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    @property
    def running(self) -> bool: ...
    @property
    def callback(self) -> Callable[[list[Completion]], object] | None: ...
    @callback.setter
    def callback(self, value: Callable[[list[Completion]], object] | None) -> None: ...
    @property
    def exception_handler(self) -> Callable[[dict[str, object]], object] | None: ...
    @exception_handler.setter
    def exception_handler(self, value: Callable[[dict[str, object]], object] | None) -> None: ...
    @property
    def pre_submit(self) -> Callable[[Completion], object] | None: ...
    @pre_submit.setter
    def pre_submit(self, value: Callable[[Completion], object] | None) -> None: ...
    def close(self) -> None: ...
    def serve_completions(self) -> None: ...
    def stop_serving(self) -> None: ...
    def reset_serving(self) -> None: ...
    def break_wait(self) -> None: ...
    def wait_idle(self, timeout: float | None = None) -> bool: ...
    def create_buf_group(self, buffer_size: int, buffer_count: int) -> BufGroup: ...
    def create_buf_view(self, buf_group: BufGroup, buffer_id: int, length: int) -> BufView: ...
    def submit_recv(self, fd: int, buf: Any, user_data: object = None) -> Completion: ...
    def submit_recv_buf(self, fd: int, buf_group: BufGroup, user_data: object = None, flags: int = 0) -> Completion: ...
    # METH_FASTCALL at the C layer: keyword arguments are not accepted.
    def submit_recv_multishot(
        self,
        fd: int,
        buf_group: BufGroup,
        user_data: object = None,
        flags: int = 0,
        base_sequence: int = 0,
        /,
    ) -> Completion: ...
    def submit_send(self, fd: int, data: Any, user_data: object = None, flags: int = 0, /) -> Completion: ...
    def submit_send_zc(
        self, fd: int, data: Any, user_data: object = None, flags: int = 0, zc_flags: int = 0, /
    ) -> Completion: ...
    def submit_recvmsg(self, fd: int, buf: Any, user_data: object = None) -> Completion: ...
    def submit_sendto(
        self, fd: int, data: Any, address: Any, user_data: object = None, flags: int = 0
    ) -> Completion: ...
    def submit_sendmsg(
        self, fd: int, data: Any, address: Any = None, user_data: object = None, flags: int = 0
    ) -> Completion: ...
    def submit_sendmsg_zc(
        self, fd: int, data: Any, address: Any = None, user_data: object = None, flags: int = 0
    ) -> Completion: ...
    def submit_accept(self, fd: int, user_data: object = None, flags: int = 0) -> Completion: ...
    def submit_accept_multishot(
        self, fd: int, user_data: object = None, flags: int = 0, base_sequence: int = 0, /
    ) -> Completion: ...
    def submit_connect(self, fd: int, address: Any, user_data: object = None) -> Completion: ...
    def submit_poll(self, fd: int, mask: int, user_data: object = None) -> Completion: ...
    def submit_poll_multishot(self, fd: int, mask: int, user_data: object = None) -> Completion: ...
    def submit_poll_remove(self, completion: Completion, user_data: object = None) -> Completion: ...
    def submit_cancel(self, completion: Completion, user_data: object = None) -> Completion: ...
    def submit_shutdown(self, fd: int, how: int, user_data: object = None) -> Completion: ...
    def submit_close(self, fd: int, user_data: object = None) -> Completion: ...
    def submit_read(self, fd: int, buf: Any, offset: FileOffset, user_data: object = None) -> Completion: ...
    def submit_write(self, fd: int, data: Any, offset: FileOffset, user_data: object = None) -> Completion: ...
    def submit_openat(
        self, path: str, flags: int, mode: int = 0, user_data: object = None, dfd: int = ...
    ) -> Completion: ...
    def submit_statx(
        self, dfd: int, path: str, flags: int, mask: int, buf: Any, user_data: object = None
    ) -> Completion: ...
    def submit_statx_fdsize(self, fd: int, user_data: object = None) -> Completion: ...
    def submit_socket(
        self, domain: int, type: int, protocol: int = 0, flags: int = 0, user_data: object = None
    ) -> Completion: ...
    def wait(self, timeout: float | None = None) -> list[Completion] | None: ...
    def __enter__(self) -> Ring: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

def probe(entries: int = 2, flags: int = 0) -> dict[str, bool]: ...
def statx_st_size(buf: Any) -> int: ...
