import enum
from types import TracebackType
from collections.abc import Callable
from typing import Any

__liburing_version__: str
__compiled_liburing_version__: str
__compiled_liburing_version_info__: tuple[int, int]
C_API_ABI_VERSION: int
C_API_FEATURE_CORE: int
C_API_FEATURES: int
IORING_SETUP_CQSIZE: int
IORING_SETUP_CLAMP: int
IORING_SETUP_COOP_TASKRUN: int
IORING_SETUP_TASKRUN_FLAG: int
IORING_SETUP_SINGLE_ISSUER: int
IORING_SETUP_DEFER_TASKRUN: int
IORING_CQE_F_MORE: int
IORING_CQE_F_NOTIF: int
IORING_SEND_ZC_REPORT_USAGE: int
IORING_NOTIF_USAGE_ZC_COPIED: int
COMPLETION_KIND_RECV: int
COMPLETION_KIND_RECV_MULTISHOT: int
COMPLETION_KIND_SEND: int
COMPLETION_KIND_SEND_ZC: int
COMPLETION_KIND_WAKE: int
COMPLETION_KIND_SENDTO: int
COMPLETION_KIND_RECVMSG: int
COMPLETION_KIND_ACCEPT: int
COMPLETION_KIND_CONNECT: int
COMPLETION_KIND_CANCEL: int
COMPLETION_KIND_SHUTDOWN: int
COMPLETION_KIND_CLOSE: int
COMPLETION_KIND_SENDMSG: int
COMPLETION_KIND_SENDMSG_ZC: int
COMPLETION_KIND_SOCKET: int

class CompletionKind(enum.IntEnum):
    RECV = 1
    SEND = 2
    WAKE = 3
    SENDTO = 4
    RECVMSG = 5
    ACCEPT = 6
    CONNECT = 7
    CANCEL = 8
    SHUTDOWN = 9
    CLOSE = 10
    SENDMSG = 11
    SOCKET = 12
    RECV_MULTISHOT = 13
    SEND_ZC = 14
    SENDMSG_ZC = 15

class SubmissionQueueFull(RuntimeError): ...

class Completion:
    @property
    def user_data(self) -> object: ...
    @property
    def kind(self) -> CompletionKind: ...
    @property
    def res(self) -> int: ...
    @property
    def flags(self) -> int: ...
    @property
    def result(self) -> object: ...
    @property
    def sequence(self) -> int: ...

class Ring:
    def __init__(self, entries: int = 8, flags: int = 0) -> None: ...
    @property
    def fd(self) -> int: ...
    @property
    def features(self) -> int: ...
    @property
    def sq_entries(self) -> int: ...
    @property
    def cq_entries(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    @property
    def running(self) -> bool: ...
    @property
    def callback(self) -> Callable[[Completion], object] | None: ...
    @callback.setter
    def callback(self, value: Callable[[Completion], object] | None) -> None: ...
    def close(self) -> None: ...
    def serve_completions(self) -> None: ...
    def stop_serving(self) -> None: ...
    def reset_serving(self) -> None: ...
    def break_wait(self) -> None: ...
    def submit_recv(self, fd: int, buf: Any, user_data: object = None) -> Completion: ...
    def submit_recv_multishot(
        self, fd: int, buffer_size: int, buffer_count: int, user_data: object = None, flags: int = 0
    ) -> Completion: ...
    def submit_send(self, fd: int, data: Any, user_data: object = None, flags: int = 0) -> Completion: ...
    def submit_send_zc(
        self, fd: int, data: Any, user_data: object = None, flags: int = 0, zc_flags: int = 0
    ) -> Completion: ...
    def submit_recvmsg(self, fd: int, buf: Any, user_data: object = None) -> Completion: ...
    def submit_sendto(
        self, fd: int, data: Any, address: Any, user_data: object = None, flags: int = 0
    ) -> Completion: ...
    def submit_sendmsg(
        self, fd: int, data: Any, address: Any = None, user_data: object = None, flags: int = 0
    ) -> Completion: ...
    def submit_sendmsg_zc(
        self, fd: int, data: Any, address: Any = None, user_data: object = None, flags: int = 0
    ) -> Completion: ...
    def submit_accept(self, fd: int, user_data: object = None, flags: int = 0) -> Completion: ...
    def submit_accept_multishot(self, fd: int, user_data: object = None, flags: int = 0) -> Completion: ...
    def submit_connect(self, fd: int, address: Any, user_data: object = None) -> Completion: ...
    def submit_cancel(self, completion: Completion) -> Completion: ...
    def submit_shutdown(self, fd: int, how: int, user_data: object = None) -> Completion: ...
    def submit_close(self, fd: int, user_data: object = None) -> Completion: ...
    def submit_socket(
        self, domain: int, type: int, protocol: int = 0, flags: int = 0, user_data: object = None
    ) -> Completion: ...
    def wait(self, timeout: float | None = None) -> Completion | None: ...
    def __enter__(self) -> Ring: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

def probe(entries: int = 2, flags: int = 0) -> dict[str, bool]: ...
