from __future__ import annotations

from contextvars import Context
from types import FrameType
from typing import Any, Callable, Final, TypeVar, overload

_T_tealet = TypeVar("_T_tealet", bound="tealet")

__version__: str

C_API_ABI_VERSION: Final[int]
PYTEALET_DEFER_DELETE: Final[int]
PYTEALET_WITH_PENDING_FRAME_INTROSPECTION: Final[int]
STATE_NEW: Final[int]
STATE_STUB: Final[int]
STATE_RUN: Final[int]
STATE_EXIT: Final[int]
STATE_PREPARED: Final[int]
_C_API: object

class TealetError(Exception): ...
class DefunctError(TealetError): ...

class PanicError(TealetError):
    def result(self) -> object: ...
    def exception(self) -> BaseException | None: ...

class InvalidError(TealetError): ...
class ThreadMismatchError(InvalidError): ...
class StateError(TealetError): ...
class TealetExit(BaseException): ...

class tealet:
    link: Any
    state: int
    frame: FrameType | None
    context: Context | None
    thread_id: int

    def __init__(self) -> None: ...
    def stub(self) -> tealet: ...
    def set_stub(self, source: tealet, duplicate: bool = True) -> tealet: ...
    def duplicate(self) -> tealet: ...
    def current(self) -> tealet: ...
    def previous(self) -> tealet | None: ...
    def main(self) -> tealet: ...
    def is_foreign(self) -> bool: ...
    def is_main(self) -> bool: ...
    def resolve_target(
        self,
        result: object,
        exc: BaseException | None,
        exc_target: tealet | None,
    ) -> tuple[tealet, object] | tuple[tealet, object, bool]: ...
    def prepare(self, function: Callable[..., object]) -> tealet: ...
    run: Any
    def switch(self, arg: object = None, panic: bool = False) -> object: ...
    def set_pending_exception(
        self, exception: BaseException | type[BaseException], fallback: tealet | None = None
    ) -> None: ...
    throw: Any
    def _unlink(self) -> None: ...

def current() -> tealet: ...
def main() -> tealet: ...
def get_tealet_factory() -> Callable[[], tealet]: ...
@overload
def set_tealet_factory(factory: Callable[[], _T_tealet]) -> _T_tealet: ...
@overload
def set_tealet_factory(factory: None) -> tealet: ...
def previous() -> tealet | None: ...
def thread_reap(cleanup_passes: int = 3, kill_exc: object = None) -> list[tealet]: ...
def thread_sweep() -> list[tealet]: ...
def thread_active() -> list[tealet]: ...
def thread_kill(cleanup_passes: int = 3, kill_exc: object = None) -> list[tealet]: ...
def error_was_remote() -> bool: ...
def hide_frame(
    function: Callable[..., object], args: tuple[Any, ...] = (), kwargs: dict[str, Any] | None = None
) -> object: ...
@overload
def frame_introspection() -> bool: ...
@overload
def frame_introspection(enabled: bool) -> bool: ...
